# Generated by Django 3.1.1 on 2021-04-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0002_auto_20200915_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='temperory', upload_to='movie_posters/'),
            preserve_default=False,
        ),
    ]
