# Generated by Django 3.2.3 on 2021-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='status',
            field=models.IntegerField(choices=[(1, 'SALE_NOT_STARTED_YET'), (2, 'SALE_OPEN'), (3, 'TICKETS_SOLD'), (4, 'SALE_CLOSED'), (5, 'MOVIE_PLAYED'), (6, 'SHOW_CANCELED')]),
        ),
    ]
